[package]
name = "windows_netstat"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.48", features = [
    "Win32_NetworkManagement_IpHelper", 
    "Win32_Foundation", 
    "Win32_System_Threading"
] }